### ISSUE TITLE
Error "platform" not defined

### ISSUE THREAD

**Issue by fildotsh** [flashnuke/wifi-deauth#20]
`
Traceback (most recent call last):
  File "/usr/bin/wifi-deauth", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.12/site-packages/wifi_deauth/wifi_deauth.py", line 392, in main
    if "linux" not in platform:
                      ^^^^^^^^
NameError: name 'platform' is not defined. Did you forget to import 'platform'?`

**Comment by flashnuke** [comment]
I'm not sure why it says not defined, but `platform` might be ambiguous in this context... as it's a variable defines by `sys` rather than a library
anyhow, while I couldn't reproduce this, I believe you'd want to give this a try: https://github.com/flashnuke/wifi-deauth/pull/21

simply pull latest and try again

also, have you run the code directly (`python3 ....`) or did you first install (`pip3 install ...`)?
